### ISSUE TITLE
Plugin throws Exceptions when no GPG keys are available

### ISSUE THREAD

**Issue by Tangresh** [inventage/nexus-apt-plugin#1]
If the plugin is installed but the capabilities are not configured at all, i.e. all empty fields, the plugin throws lots of Exceptions when a new package is loaded into the repository.

It should be possible to handle this gracefully.

**Comment by bedge** [comment]
Is this the same problem (with version 1.0.1):
```
2015-01-20 18:53:54 ERROR [qtp608963866-94] jenkins com.inventage.nexusaptplugin.MacPluginEventInspector - e
org.sonatype.nexus.proxy.LocalStorageException: Got exception during storing on path "releases:/apt-key.gpg.key" (while writing to hiddenTarget: "/home/nexus/sonatype-work/nexus/storage/releases/.nexus/tmp/apt-key.gpg.keynx-tmp5280553067672094625.nx-upload")
        at org.sonatype.nexus.proxy.storage.local.fs.DefaultFSPeer.storeItem(DefaultFSPeer.java:157) ~[nexus-core-2.11.1-01.jar:2.11.1-01]
        at org.sonatype.nexus.proxy.storage.local.fs.DefaultFSLocalRepositoryStorage.storeItem(DefaultFSLocalRepositoryStorage.java:354) ~[nexus-core-2.11.1-01.jar:2.11.1-01]
        at org.sonatype.nexus.proxy.repository.AbstractRepository.storeItem(AbstractRepository.java:1009) [nexus-core-2.11.1-01.jar:2.11.1-01]
        at org.sonatype.nexus.proxy.maven.AbstractMavenRepository.storeItem(AbstractMavenRepository.java:463) [nexus-core-2.11.1-01.jar:2.11.1-01]
        at com.inventage.nexusaptplugin.MacPluginEventInspector.updateOrInstallStorageItem(MacPluginEventInspector.java:178) [nexus-apt-plugin-1.0.1/:na]
        at com.inventage.nexusaptplugin.MacPluginEventInspector.updateFileModificationDate(MacPluginEventInspector.java:155) [nexus-apt-plugin-1.0.1/:na]
        at com.inventage.nexusaptplugin.MacPluginEventInspector.updateDebItemInRepository(MacPluginEventInspector.java:104) [nexus-apt-plugin-1.0.1/:na]
        at com.inventage.nexusaptplugin.MacPluginEventInspector.onRepositoryItemEventStore(MacPluginEventInspector.java:94) [nexus-apt-plugin-1.0.1/:na]
        at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_72]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_72]
```

**Comment by Tangresh** [comment]
Yes, same problem. But that should not influence the generation of the Packages.gz file.
