### ISSUE TITLE
Empty file Packages

### ISSUE THREAD

**Issue by il77** [inventage/nexus-apt-plugin#20]
Hello. Please help me. I try to use Nexus as apt repository, but when .deb files uploaded APT plugin don`t insert information into "packages". What can I do to plugin work correct? Thank.

Version: Nexus Repository Manager OSS 2.12.1-01
              APTplugin 1.1.1

File uploaded by command:
curl -v -F "r=apt" -F "hasPom=false" -F "e=deb" -F "g=xxx" -F "a=yyy" -F "v=1.0.0" -F "p=deb" -F "file=@./file.deb" -u user:pswd http://10.69.22.100:8081/nexus/service/local/artifact/maven/content

or

curl -v -F "hasPom=false" -F "r=apt" -F "g=xxx" -F "a=yyy" -F "v=1.0.0" -F "p=deb" -F "file=@file.deb" -u user:pwsd http://10.69.22.100:8081/nexus/content/repositories/apt/xxx/yyy/1.0.0/file-1.0.0.deb

**Comment by Tangresh** [comment]
When you download the .deb file through the Nexus UI, do you get the same file back that you uploaded?
Also, what are the contents of `http://10.69.22.100:8081/nexus/service/local/artifact/maven/content/Release`?

**Comment by 414n** [comment]
I'm having the same issue, but with deb packages created via the [jdeb maven plugin](https://github.com/tcurdt/jdeb) and uploaded to the repo during the `deploy` phase.
Even forcing an `Update index` operation on the relevant nexus repo, the `Packages` and `Packages.gz` files are still empty.
What I get in the log upon forcing the index update is this:
```
2016-10-01 15:58:25,961+0200 INFO  [pxpool-1-thread-2] admin org.sonatype.nexus.index.tasks.UpdateIndexTask - Scheduled task (UpdateIndexTask) started :: Updating repository index "Snapshots" from path / and below.
2016-10-01 15:58:26,087+0200 WARN  [pxpool-1-thread-2] admin org.sonatype.nexus.index.DefaultIndexerManager - Could not perform index operation on repository snapshots
java.lang.Exception: This is an artificial exception that provides caller backtrace.
	at org.sonatype.nexus.index.DefaultIndexerManager.sharedSingle(DefaultIndexerManager.java:2323) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:1001) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:961) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:938) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.tasks.ReindexTaskHandlerLegacy.reindexRepository(ReindexTaskHandlerLegacy.java:61) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.tasks.AbstractIndexerTask.doRun(AbstractIndexerTask.java:68) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.scheduling.AbstractNexusTask.call(AbstractNexusTask.java:163) [nexus-core-2.13.0-01.jar:2.13.0-01]
	at org.sonatype.scheduling.DefaultScheduledTask.call(DefaultScheduledTask.java:418) [nexus-scheduler-2.13.0-01.jar:2.13.0-01]
	at org.sonatype.nexus.threads.MDCAwareCallable.call(MDCAwareCallable.java:44) [nexus-core-2.13.0-01.jar:2.13.0-01]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.3.jar:1.2.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
2016-10-01 15:58:26,087+0200 WARN  [pxpool-1-thread-2] admin org.sonatype.nexus.index.DefaultIndexerManager - Could not perform index operation on repository snapshots
java.lang.Exception: This is an artificial exception that provides caller backtrace.
	at org.sonatype.nexus.index.DefaultIndexerManager.shared(DefaultIndexerManager.java:2302) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.DefaultIndexerManager.publishRepositoryIndex(DefaultIndexerManager.java:1441) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:964) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:938) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.tasks.ReindexTaskHandlerLegacy.reindexRepository(ReindexTaskHandlerLegacy.java:61) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.index.tasks.AbstractIndexerTask.doRun(AbstractIndexerTask.java:68) [nexus-indexer-lucene-plugin-2.13.0-01/:na]
	at org.sonatype.nexus.scheduling.AbstractNexusTask.call(AbstractNexusTask.java:163) [nexus-core-2.13.0-01.jar:2.13.0-01]
	at org.sonatype.scheduling.DefaultScheduledTask.call(DefaultScheduledTask.java:418) [nexus-scheduler-2.13.0-01.jar:2.13.0-01]
	at org.sonatype.nexus.threads.MDCAwareCallable.call(MDCAwareCallable.java:44) [nexus-core-2.13.0-01.jar:2.13.0-01]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.3.jar:1.2.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
2016-10-01 15:58:26,088+0200 INFO  [pxpool-1-thread-2] admin org.sonatype.nexus.index.tasks.UpdateIndexTask - Scheduled task (UpdateIndexTask) finished :: Updating repository index "Snapshots" from path / and below. (started 2016-10-01T15:58:25+02:00, runtime 0:00:00.127)
2016-10-01 15:58:26,162+0200 INFO  [pxpool-1-thread-2] admin org.sonatype.nexus.configuration.application.DefaultNexusConfiguration - Applying Nexus Configuration due to changes in [Scheduled Tasks] made by *TASK...
```
Any advice?
I'm running a 2.13.0-01 nexus instance on OpenJDK 1.8.0_91

**Comment by jharley** [comment]
I'm having the same issue: Nexus 2.11.4, Oracle JDK 1.8.0-b132, nexus-apt-plugin 1.1.2

I've uploaded my deb via curl in a variety of ways with the same result, but most recently:

```bash
curl -v -u user:pass -F "hasPom=false" --upload-file $1 \
http://nexus.mycorp.tld:8081/nexus/content/repoistories/apt/mydeb.deb
```

( I've tried with `-F "r=apt" -F "p=deb"` in there as well )

Nexus returns `201 Created` quite happily, and the deb is placed in the repository (maven1 type -- I wasn't sure which to make, to be honest).  If I browse to the repo, the Packages file is empty, and Release only contains the checksums for the empty Packages and it's gzip'd peer:

```
Date: Thu, 24 Nov 2016 20:09:54 +0000
MD5Sum:
 d41d8cd98f00b204e9800998ecf8427e  0 Packages
 3970e82605c7d109bb348fc94e9eecc0 20 Packages.gz
SHA1:
 da39a3ee5e6b4b0d3255bfef95601890afd80709  0 Packages
 e03849ea786b9f7b28a35c17949e85a93eb1cff1 20 Packages.gz
SHA256:
 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  0 Packages
 f5d031af01f137ae07fa71720fab94d16cc8a2a59868766002918b7c240f3967 20 Packages.gz
```

The deb is the one I uploaded (checksum matches, `deb -I` shows the proper control file information, and the installs fine with `deb -i`)

I don't see anything of note in the Nexus logs either.

Thoughts?
