### ISSUE TITLE
Apt plugin does not handle xz compression for control files

### ISSUE THREAD

**Issue by cswingler** [inventage/nexus-apt-plugin#34]
Hi there!

We just spent some time trying to track down why our repository was broken, and finally figured out that a newer package we uploaded was failing to be parsed because its control files were in a file named `control.tar.xz`, not `control.tar.gz`.

https://github.com/inventage/nexus-apt-plugin/blob/1.1.x/src/main/java/com/inventage/nexusaptplugin/deb/GetControl.java#L22

The error message thrown is not particularly helpful:

```
2018-08-13 18:31:44,697+0000 ERROR [esh-1-thread-14] ops-deployer org.sonatype.nexus.index.events.IndexerManagerEventInsp
ector - Could not maintain index for repository ops-trusty!
java.lang.NullPointerException: null
        at java.util.LinkedList.addAll(LinkedList.java:406)
        at java.util.LinkedList.addAll(LinkedList.java:385)
        at java.util.LinkedList.<init>(LinkedList.java:117)
        at com.inventage.nexusaptplugin.deb.DebControlParser.parse(DebControlParser.java:15)
        at com.inventage.nexusaptplugin.DebianIndexCreator.populateArtifactInfo(DebianIndexCreator.java:136)
        at org.apache.maven.index.ArtifactContext.createDocument(ArtifactContext.java:184)
        at org.apache.maven.index.DefaultIndexerEngine.update(DefaultIndexerEngine.java:73)
        at org.apache.maven.index.DefaultIndexer.addArtifactsToIndex(DefaultIndexer.java:110)
        at org.apache.maven.index.DefaultNexusIndexer.addArtifactToIndex(DefaultNexusIndexer.java:338)
        at org.sonatype.nexus.index.DefaultIndexerManager.addItemToIndex(DefaultIndexerManager.java:787)
        at org.sonatype.nexus.index.DefaultIndexerManager.access$800(DefaultIndexerManager.java:188)
        at org.sonatype.nexus.index.DefaultIndexerManager$5.run(DefaultIndexerManager.java:739)
        at org.sonatype.nexus.index.DefaultIndexerManager.sharedSingle(DefaultIndexerManager.java:2320)
        at org.sonatype.nexus.index.DefaultIndexerManager.addItemToIndex(DefaultIndexerManager.java:733)
        at org.sonatype.nexus.index.events.IndexerManagerEventInspector.inspectForIndexerManager(IndexerManagerEventInspe
ctor.java:94)
        at org.sonatype.nexus.index.events.IndexerManagerEventInspector.on(IndexerManagerEventInspector.java:73)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.AsyncEventBus.access$001(AsyncEventBus.java:34)
        at com.google.common.eventbus.AsyncEventBus$1.run(AsyncEventBus.java:117)
        at org.sonatype.nexus.threads.MDCAwareRunnable.run(MDCAwareRunnable.java:41)
        at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
        at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

Ideally, the plugin should handle `xz` files, but if not, a more useful error message would be great.

**Comment by Tangresh** [comment]
Can you provide a patch for either xz support or a better error message?

We are not actively using this plugin anymore and therefore have practically no time to develop it.
Also, you might want to consider moving over to Nexus 3 and its apt plugin: http://exchange.sonatype.com/details?extension=4719699238

**Comment by derjohn** [comment]
FYI: The V3 plugin supports xz for sure in the current version.
